export default {
  COMMENTS_LOAD: 'COMMENTS_LOAD',
  COMMENTS_LOAD_SUCCESS: 'COMMENTS_LOAD_SUCCESS',
  COMMENTS_CLEAR: 'COMMENTS_CLEAR',
  COMMENTS_ADD: 'COMMENTS_ADD',
  COMMENTS_UPDATE: 'COMMENTS_UPDATE',
  COMMENTS_CREATE: 'COMMENTS_CREATE',
  COMMENTS_LIKE_SET: 'COMMENTS_LIKE_SET'
}
